export const SUCCESS = "SUCCESS"
export const FAIL = "FAIL"
export const LOADING = "LOADING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const REGISTER_ERROR = "REGISTER_ERROR"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_LOADING = "REGISTER_LOADING"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_ERROR = "LOGOUT_ERROR"
export const OUTREACH_SUCCESS = "OUTREACH_SUCCESS"
export const ERROR = "ERROR"
export const SENTIMENT_SUCCESS = "SENTIMENT_SUCCESS"
export const BUZZ_SUCCESS = "BUZZ_SUCCESS"
export const WORDLCLOUD_SUCCESS = "WORDLCLOUD_SUCCESS"
export const MENTIONS_SUCCESS = "MENTIONS_SUCCESS"
export const GET_IDENTITY = "GET_IDENTITY"









